services:
  webapi:
    build:
      context: .      
      dockerfile: Dockerfile
    image: ktapccreferencedataapi-webapi
    container_name: kta_reference_data_api
    ports:
      - "8082:8080"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: kta_reference_data_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"